### ISSUE TITLE
Packages having 2 characters name are not being searched. 

### ISSUE THREAD

**Issue by gauravksoni** [arve0/download-size#6]
Tried searching for package `he` it shows nothing. https://www.npmjs.com/package/he

**Comment by arve0** [comment]
Thanks for reporting. `download-size he` works here: https://asciinema.org/a/F66AY9s6AMzpat1SP8AYXQYEL

Did you use the web-client? This is the repo for the command line interface (CLI).

**Comment by arve0** [comment]
For now you could work-around the issue by typing the URL manually: https://arve0.github.io/npm-download-size/#he

Moved the issue to were it belongs.
