### ISSUE TITLE
Unable to parse unencoded URLs

### ISSUE THREAD

**Issue by alexvdvalk** [arve0/download-size#8]
URL Encoding needs to be gracefully handled

Not working:
- download-size @angular/core
- download-size "@angular/core"

Working:
download-size %40angular%2Fcore

Solution:
line 32: 
pkgName = encodeURIComponent(pkgName);

**Comment by arve0** [comment]
Thanks for reporting👍

Until fixed, you can use https://arve0.github.io/npm-download-size/

**Comment by arve0** [comment]
Thanks for reporting. Should be fixed in `v1.3.5`.
